#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"

layout (local_size_x = 8, local_size_y = 8) in;

const float PI = 3.14159265359;

layout (push_constant) uniform constants
{
	vec2 imageSize;
	uint texture_id;
	uint image_id;
	float roughness;
} pc;

float RadicalInverse_VdC(uint bits) 
{
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10; // / 0x100000000
}

vec2 Hammersley(uint i, uint N)
{
    return vec2(float(i)/float(N), RadicalInverse_VdC(i));
} 

vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float linearRoughness)
{
    float a = linearRoughness;
	
    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);
	
    // from spherical coordinates to cartesian coordinates
    vec3 H;
    H.x = cos(phi) * sinTheta;
    H.y = sin(phi) * sinTheta;
    H.z = cosTheta;
	
    // from tangent-space vector to world-space sample vector
    vec3 up = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);
	
    vec3 sampleVec = tangent * H.x + bitangent * H.y + N * H.z;
    return normalize(sampleVec);
}  

float V_SmithGGXCorrelated(float NdotV, float NdotL, float linearRoughness)
{
	float a2 = linearRoughness * linearRoughness;
	float GGXV = NdotL * sqrt(NdotV * NdotV * (1.0 - a2) + a2);
	float GGXL = NdotV * sqrt(NdotL * NdotL * (1.0 - a2) + a2);
	return 0.5 / (GGXV + GGXL);
}

vec2 IntegratedBRDF(float NdotV, float perceptualRoughness)
{
	vec3 V = vec3(0.0);
	V.x = sqrt(1.0 - NdotV * NdotV);
    V.y = 0.0;
    V.z = NdotV;

	vec3 N = vec3(0.0, 0.0, 1.0);
	float linearRoughness = perceptualRoughness * perceptualRoughness;

	float scale = 0.0;
	float bias = 0.0;

	uint sampleCount = 1024;
	for (uint i = 0; i < sampleCount; i++)
	{
		vec2 Xi = Hammersley(i, sampleCount);
		vec3 H = ImportanceSampleGGX(Xi, N, linearRoughness);
		vec3 L = normalize(2.0 * dot(V,H) * H - V);

		float NdotL = max(L.z, 0.0);
		float NdotH = max(H.z, 0.0);
		float VdotH = max(dot(V, H), 0.0);

		if (NdotL > 0.0)
		{
			float V_pdf = V_SmithGGXCorrelated(NdotV, NdotL, linearRoughness) * VdotH * NdotL / NdotH;
			float Fc = pow(1.0 - VdotH, 5.0);
			scale += V_pdf * (1.0 - Fc);
			bias += V_pdf * Fc;
		}
	}

	return 4.0 * vec2(scale, bias) / float(sampleCount);
}

void main()
{
	vec2 texelCoord = vec2(gl_GlobalInvocationID.xy);
	vec2 uv = (texelCoord + vec2(0.5)) / pc.imageSize;
	
	vec2 color = IntegratedBRDF(uv.x, uv.y);
	
	imageStore(images_rg16f[pc.image_id], ivec2(texelCoord), vec4(color, 0.0, 1.0));
}