#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

#include "samplers.glsl"

layout (local_size_x = 32, local_size_y = 32) in;

layout(set = 0, binding = 0, r32f) uniform image2D allImages[];
layout(set = 1, binding = 0) uniform texture2D allTextures[];
layout(set = 2, binding = 0) uniform sampler samplers[];

layout(push_constant) uniform constants
{
	ivec2 imageSize;
	uint texture_id;
	uint image_id;
	uint lod;
} pc;

void main()
{
	ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
	
	if (pos.x < int(pc.imageSize.x) || pos.y < int(pc.imageSize.y))
	{
		vec2 uv = vec2(pos) + vec2(0.5);
		uv = uv / pc.imageSize;
		
		float depth = textureLod(sampler2D(allTextures[pc.texture_id], samplers[DEPTH_REDUCTION_SAMPLER]), uv, pc.lod).r; 
	
		imageStore(allImages[pc.image_id], pos, vec4(depth));
	}
}