#version 450

#extension GL_EXT_nonuniform_qualifier : require

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba32f) uniform image2DArray allImages[];
layout(set = 1, binding = 0) uniform texture2D allTextures[];
layout(set = 2, binding = 0) uniform sampler samplers[];

const vec2 invAtan = vec2(0.1591, 0.3183);

// push constant block
layout (push_constant) uniform constants
{
	uint texture_id;
	uint image_id;
} pc;

vec2 sampleSphericalMap(vec3 v)
{
	vec2 uv = vec2(atan(v.z, v.x), asin(v.y));
	uv *= invAtan;
	uv += 0.5;
	uv.y = 1.0 - uv.y;
	return uv;
}

void main()
{
	vec3 direction = vec3(0.0);

	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size = imageSize(allImages[pc.image_id]).xy;
	vec2 uv = vec2(texelCoord + 0.5)  / vec2(size);
	uv = uv * 2.0 - 1.0;

	for (int face = 0; face < 6; face++)
	{
		switch (face)
		{
			case 0: direction = normalize(vec3(1.0, -uv.y, -uv.x)); break; // +X
			case 1: direction = normalize(vec3(-1.0, -uv.y, uv.x)); break; // -X
			case 2: direction = normalize(vec3(uv.x, 1.0, uv.y)); break; // +Y
			case 3: direction = normalize(vec3(uv.x, -1.0, -uv.y)); break; // -Y
			case 4: direction = normalize(vec3(uv.x, -uv.y, 1.0)); break; // +Z
			case 5: direction = normalize(vec3(-uv.x, -uv.y, -1.0)); break; // -Z
			default: direction = vec3(0.0); break; // Should not happen
		}

		vec2 sample_uv = sampleSphericalMap(direction);
		vec4 color = texture(sampler2D(allTextures[pc.texture_id], samplers[0]), sample_uv);
		
		imageStore(allImages[pc.image_id], ivec3(texelCoord, face), color);
	}
}