#version 450

#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

layout (local_size_x = 256) in;

struct ObjectData
{
	mat4 worldMatrix;
	vec3 origin;
	uint materialID;
	vec3 extent;
	uint padding;
};

layout(buffer_reference, std430) readonly buffer ObjectBuffer
{ 
	ObjectData objects[];
};

struct GPUInstance
{
	uint object_id;
	uint batch_id;
};

layout(buffer_reference, std430) readonly buffer gInstanceBuffer
{ 
	GPUInstance instances[];
};

struct DrawCommand
{
	uint index_count;
	uint instance_count;
	uint first_index;
	int vertex_offset;
	uint first_instance;
	uint pipeline_id;
};

layout(buffer_reference, std430) buffer DrawCommandsBuffer
{ 
	DrawCommand commands[];
};

layout(buffer_reference, std430) buffer InstanceBuffer
{
	uint instances[];
};
	
layout(push_constant) uniform constants
{
	vec4 frustum_planes[6];
	ObjectBuffer objectBuffer;
	gInstanceBuffer ginstanceBuffer;
	DrawCommandsBuffer drawCommandsBuffer;
	InstanceBuffer instanceBuffer;
	uint count;
} pc;

bool is_visible(uint object_id)
{
	ObjectData obj = pc.objectBuffer.objects[object_id];
	vec3 center = vec3(obj.worldMatrix * vec4(obj.origin, 1.0));
	
	vec3 right = vec3(obj.worldMatrix[0] * obj.extent.x);
	vec3 up = vec3(obj.worldMatrix[1] * obj.extent.y);
	vec3 forward = vec3(obj.worldMatrix[2] * obj.extent.z);
	
	// recompute AABB
	vec3 extent = vec3(0.0);
	extent.x = abs(right.x) + abs(up.x) + abs(forward.x);
	extent.y = abs(right.y) + abs(up.y) + abs(forward.y);
	extent.z = abs(right.z) + abs(up.z) + abs(forward.z);
	
	bool visible = true;
	
	for (uint i = 0; i < 6; i++)
	{
		vec3 normal = pc.frustum_planes[i].xyz;
		float distance = pc.frustum_planes[i].w;
			
		// project radius (extent) of box onto line
		float r = dot(extent, abs(normal));
		
		// distance of box center from plane
		float s = dot(center, normal) + distance;
		
		visible = visible && (s >= -r);
	}
	
	return visible;
}

void main()
{
	uint g_id = gl_GlobalInvocationID.x;
	
	if (g_id < pc.count)
	{
		GPUInstance instance = pc.ginstanceBuffer.instances[g_id];
		uint object = instance.object_id;
		uint batch = instance.batch_id;
		
		if (is_visible(object))
		{
			uint count = atomicAdd(pc.drawCommandsBuffer.commands[batch].instance_count, 1);
			
			uint instance_index = pc.drawCommandsBuffer.commands[batch].first_instance + count; // req for instancing support
			
			pc.instanceBuffer.instances[instance_index] = object;
		}
	}
}