#version 450

#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

layout (local_size_x = 256) in;

struct ObjectData
{
	mat4 worldMatrix;
	//vec3 origin;
	//float radius;
	uint materialID;
	//vec3 extent;
	uint padding[3];
};

struct MeshData
{
	vec3 center;
	float radius;
	uint first_index;
	uint index_count;
	uint padding[2];
};

struct GPUInstance
{
	uint mesh_id;
	uint object_id;
};

layout(buffer_reference, std430) readonly buffer ObjectBuffer
{ 
	ObjectData objects[];
};

layout(buffer_reference, std430) readonly buffer MeshBuffer
{ 
	MeshData meshes[];
};

struct DrawCommand
{
	uint index_count;
	uint instance_count;
	uint first_index;
	int vertex_offset;
	uint first_instance;
};

layout(buffer_reference, std430) buffer DrawCommandsBuffer
{ 
	DrawCommand commands[];
};

layout(buffer_reference, std430) buffer CountBuffer
{
	uint count[];
};
	
layout(buffer_reference, std430) buffer VisibilityBuffer
{
	uint visible[];
};

layout(buffer_reference, std430) buffer DebugBuffer
{
	float value[];
};

layout(buffer_reference, std430) buffer InstanceBuffer
{
	GPUInstance instances[];
};

layout(push_constant) uniform constants
{
	mat4 view;
	vec4 frustum_planes;
	ObjectBuffer objectBuffer;
	MeshBuffer meshBuffer;
	InstanceBuffer instanceBuffer;
	DrawCommandsBuffer drawBuffer;
	CountBuffer countBuffer;
	VisibilityBuffer visBuffer;
	DebugBuffer debugBuffer;
	uint count;
	uint late;
	uint texture_id;
	uint occlusionEnabled;
	
	float p00;
	float p11;
	float znear;
	float zfar;
	
	vec2 resolution;
	float lod;
	
} pc;

layout(set = 0, binding = 0, r32f) uniform image2D allImages[];
layout(set = 1, binding = 0) uniform texture2D allTextures[];
layout(set = 2, binding = 0) uniform sampler samplers[];

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
// https://zeux.io/2023/01/12/approximate-projected-bounds/
bool projectSphere(vec3 c, float r, float znear, float P00, float P11, out vec4 aabb)
{
	if (c.z < r + znear)
		return false;

    vec3 cr = c * r;
    float czr2 = c.z * c.z - r * r;

    float vx = sqrt(c.x * c.x + czr2);
    float minx = (vx * c.x - cr.z) / (vx * c.z + cr.x);
    float maxx = (vx * c.x + cr.z) / (vx * c.z - cr.x);

    float vy = sqrt(c.y * c.y + czr2);
    float miny = (vy * c.y - cr.z) / (vy * c.z + cr.y);
    float maxy = (vy * c.y + cr.z) / (vy * c.z - cr.y);

    aabb = vec4(minx * P00, miny * P11, maxx * P00, maxy * P11);
    // clip space -> uv space
    aabb = aabb.xwzy * vec4(0.5f, -0.5f, 0.5f, -0.5f) + vec4(0.5f);

    return true;
}

bool frustumCulled(vec3 center, float radius)
{
	bool visible = true;
	
	// symmetrical sphere-plane distance test
	visible = visible && (center.z * pc.frustum_planes.y - abs(center.x) * pc.frustum_planes.x) >= -radius;
	visible = visible && (center.z * pc.frustum_planes.w - abs(center.y) * pc.frustum_planes.z) >= -radius;
	visible = visible && (center.z - radius <= -pc.znear) && (center.z + radius >= -pc.zfar);	
		
	return !visible;
}

bool occlusionCulled(vec3 center, float radius)
{
	vec4 aabb;
	
	if (projectSphere(vec3(center.x, center.y, -center.z), radius, pc.znear, pc.p00, pc.p11, aabb))
	{
		vec2 pixel_size = (aabb.zw - aabb.xy) * pc.resolution; 
		
		float max_dim = max(pixel_size.x, pixel_size.y);
		
		float mip = ceil(log2(max_dim));
		mip = min(mip, pc.lod); // TODO: PC
		
		float depth = textureLod(sampler2D(allTextures[pc.texture_id], samplers[4]), (aabb.zw + aabb.xy) * 0.5, mip).r;
		
		float depthSphere = pc.znear / (-center.z - radius); 
		
		return depthSphere < depth; // reverse depth
	}
}

void main()
{
	uint id = gl_GlobalInvocationID.x;
	
	if (id < pc.count)
	{
		bool late = pc.late == 1;
		bool visible_last_frame = pc.visBuffer.visible[id] == 1;
		
		if (!late && !visible_last_frame)
			return;
		
		GPUInstance instance = pc.instanceBuffer.instances[id];
		uint mesh_id = instance.mesh_id;
		uint object_id = instance.object_id;
		
		MeshData mesh = pc.meshBuffer.meshes[mesh_id];
		
		ObjectData obj = pc.objectBuffer.objects[object_id];
	
		vec3 center = vec3(pc.view * obj.worldMatrix * vec4(mesh.center, 1.0));
		float radius = mesh.radius;
		
		vec3 right = vec3(obj.worldMatrix[0]);
		vec3 up = vec3(obj.worldMatrix[1]);
		vec3 forward = vec3(obj.worldMatrix[2]);
		
		vec3 scale = vec3(length(right), length(up), length(forward));
		
		float maxScale = max(scale.z, max(scale.x, scale.y));
		radius = radius * maxScale;
		
		bool visible = !frustumCulled(center, radius);
		
		bool shouldDraw = false;
		if (!late)
			shouldDraw = visible;
		else
		{
			if (visible)
			{
				if (pc.occlusionEnabled == 1)
					visible = visible && !occlusionCulled(center, radius);
				shouldDraw = visible && !visible_last_frame;
			}
		}
		
		if (shouldDraw)
		{
			uint count = atomicAdd(pc.countBuffer.count[0], 1);
			
			pc.drawBuffer.commands[count].index_count = mesh.index_count;
			pc.drawBuffer.commands[count].instance_count = 1;
			pc.drawBuffer.commands[count].first_index = mesh.first_index;
			pc.drawBuffer.commands[count].vertex_offset = 0;
			pc.drawBuffer.commands[count].first_instance = object_id;
		}
		
		if (late)
			pc.visBuffer.visible[id] = uint(visible); 

	}
}