#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"

layout (local_size_x = 32, local_size_y = 32) in;

layout (push_constant) uniform constants
{
	vec2 image_size;
	uint texture_id;
	uint image_id;
	float roughness;
};

const float sample_delta = 0.025; 
const float PI = 3.14159265359;

void main()
{
	vec3 irradiance = vec3(0.0);

	vec3 direction = vec3(0.0);

	vec2 texel_coord = vec2(gl_GlobalInvocationID.xy);
	vec2 uv = (texel_coord + vec2(0.5)) / image_size;
	uv = uv * 2.0 - 1.0;

	uint face = gl_WorkGroupID.z;
	
	switch (face)
	{
		case 0: direction = normalize(vec3(1.0, -uv.y, -uv.x)); break; // +X
		case 1: direction = normalize(vec3(-1.0, -uv.y, uv.x)); break; // -X
		case 2: direction = normalize(vec3(uv.x, 1.0, uv.y)); break; // +Y
		case 3: direction = normalize(vec3(uv.x, -1.0, -uv.y)); break; // -Y
		case 4: direction = normalize(vec3(uv.x, -uv.y, 1.0)); break; // +Z
		case 5: direction = normalize(vec3(-uv.x, -uv.y, -1.0)); break; // -Z
		default: direction = vec3(0.0); break; 
	}
	
	vec3 N = direction;
	vec3 up = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
	vec3 T = normalize(cross(up, N));
	vec3 B = cross(N, T);

	uint sample_count = 0;
	for (float phi = 0.0; phi < (PI * 2.0); phi += sample_delta)
	{
		for (float theta = 0.0; theta < (PI * 0.5); theta += sample_delta)
		{
			vec3 temp_vec = cos(phi) * T + sin(phi) * B;
			vec3 sample_vec = cos(theta) * N + sin(theta) * temp_vec;

			irradiance += texture(samplerCube(textures_cube[texture_id], samplers[CUBE_SAMPLER]), sample_vec).xyz * cos(theta) * sin(theta); 
			sample_count++;
		}
	}

	irradiance = PI * irradiance / float(sample_count);
	
	imageStore(images_array_rgba32f[image_id], ivec3(texel_coord, face), vec4(irradiance, 1));
}