#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"
#include "buffer_references.glsl"

// 1 cluster per workgroup
layout (local_size_x = 128) in;

layout( push_constant ) uniform constants
{
	mat4 view;
	mat4 lightRot;
	ClusterBuffer clusterBuffer;
	LightBuffer lightBuffer;
	LightIndexBuffer lightIndexBuffer;
	LightGridBuffer lightGridBuffer;
	LightCountBuffer lightCountBuffer;
} pc;

float distanceSquared(vec3 a, vec3 b)
{
	vec3 d = a - b;
	return dot(d, d);
}

bool sphereAABBIntersect(AABB aabb, vec3 center, float radius)
{
	vec3 lightCenter = vec3(pc.view * pc.lightRot * vec4(center, 1.0));
	vec3 closest = clamp(lightCenter, aabb.min.xyz, aabb.max.xyz);
	
	float d = distanceSquared(closest, lightCenter);
	return d <= (radius * radius);
}

// TODO: move this to a config file
#define MAX_LIGHTS 1000

// workgroup shared
shared uint sharedOffset; 
shared uint sharedCount[gl_WorkGroupSize.x];
shared uint sharedLightList[MAX_LIGHTS];

shared uint clusterLightCount;
shared uint clusterOffset;
	
void main()
{
	uint clusterIndex = 
		gl_WorkGroupID.x 
		+ gl_NumWorkGroups.x * gl_WorkGroupID.y 
		+ gl_NumWorkGroups.x * gl_NumWorkGroups.y * gl_WorkGroupID.z;
		
	AABB clusterAABB = pc.clusterBuffer.aabb[clusterIndex];
	
	const uint batches = (MAX_LIGHTS + gl_WorkGroupSize.x - 1) / gl_WorkGroupSize.x;
	uint localLightList[batches];
	uint localLightCount = 0;
	
	// each thread performs approx MAX_LIGHTS/threads light intersection test
	for (uint batch = 0; batch < batches; batch++)
	{
		uint lightIndex = min(batch * gl_WorkGroupSize.x + gl_LocalInvocationIndex, MAX_LIGHTS);
		if (lightIndex == MAX_LIGHTS)
			break;
		
		PointLight light = pc.lightBuffer.lights[lightIndex];
		vec3 lightPos = light.pos.xyz;
		float lightRadius = light.pos.w;
		bool intersect = sphereAABBIntersect(clusterAABB, lightPos, lightRadius);
		
		if (intersect)
		{	
			localLightList[localLightCount++] = lightIndex; // record light index
		}
	}
	
	sharedOffset = 0;
	barrier(); 
	
	uint offset;
	if (localLightCount > 0)
		offset = atomicAdd(sharedOffset, localLightCount); // TODO: potentially slow per thread atomic
	
	for (uint i = 0; i < localLightCount; i++)
	{
		sharedLightList[offset + i] = localLightList[i];
	}
	
	sharedCount[gl_LocalInvocationIndex] = localLightCount;
	
	barrier(); 
	
	if (gl_LocalInvocationIndex == 0)
	{
	
		clusterLightCount = 0;
		
		// sum up total lights affecting cluster
		// TODO: use ballot
		for (int i = 0; i < gl_WorkGroupSize.x; i++)
		{
			clusterLightCount += sharedCount[i];
		}
	
		clusterOffset = atomicAdd(pc.lightCountBuffer.count, clusterLightCount);
		
		pc.lightGridBuffer.grid[clusterIndex].offset = clusterOffset;
		pc.lightGridBuffer.grid[clusterIndex].count = clusterLightCount;
	}
	
	barrier();
	
	// update global light index list
	for (uint i = gl_LocalInvocationIndex; i < clusterLightCount; i = i + gl_WorkGroupSize.x)
	{
		pc.lightIndexBuffer.indices[clusterOffset + i] = sharedLightList[i];
	}
}