#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

#include "math.glsl"

layout (local_size_x = 16, local_size_y = 16) in;

layout(set = 0, binding = 0, rgba32f) uniform image2D allImages[];
layout(set = 1, binding = 0) uniform texture2D allTextures[]; // unused
layout(set = 2, binding = 0) uniform sampler samplers[]; // unused

layout(buffer_reference, std430) buffer LuminanceBuffer
{
	uint bins[256];
};

layout(buffer_reference, std430) buffer LuminanceAvgBuffer
{
	float luminanceAvg;
};

layout( push_constant ) uniform constants
{
	LuminanceBuffer luminanceBuffer;
	LuminanceAvgBuffer luminanceAvgBuffer;
	vec2 screenSize;
	uint imageId; // HDR color attachment
	float minLogLuminance;
	float oneOverLogLuminanceRange;
	uint pixelCount;
	float tau;
	float deltaTime;
} pc;

shared uint sharedBins[256];

float getLuminance(vec3 color)
{
	return dot(color, vec3(0.2125, 0.7154, 0.0721));
}

uint colorToBin(vec3 color)
{
	float luminance = getLuminance(color);
	
	if (luminance < 0.005)
		return 0;
		
	float logLuminance = clamp((log2(luminance) - pc.minLogLuminance) * pc.oneOverLogLuminanceRange, 0.0, 1.0); // in range [0,254]
	return uint(logLuminance * 254.0 + 1.0); // map to [1,255]
}

void main()
{
	sharedBins[gl_LocalInvocationIndex] = 0;
	
	barrier();
	
	ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
	if (texelCoord.x < pc.screenSize.x && texelCoord.y < pc.screenSize.y)
	{
		vec3 color = imageLoad(allImages[pc.imageId], texelCoord).rgb;
		
		uint bin = colorToBin(color);
		
		atomicAdd(sharedBins[bin], 1);
	}
	
	barrier();
	atomicAdd(pc.luminanceBuffer.bins[gl_LocalInvocationIndex], sharedBins[gl_LocalInvocationIndex]);
}