#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

#include "mesh.glsl"

layout (local_size_x = 32) in;

layout(buffer_reference, std430) readonly buffer ObjectBuffer
{ 
	ObjectData objects[];
};

layout(buffer_reference, std430) buffer ClusterIndicesBuffer
{ 
	uint indices[];
};


layout(buffer_reference, std430) buffer CountBuffer
{
	uint count;
	uint workgroupX;
	uint workgroupY;
	uint workgroupZ;
};

layout(buffer_reference, std430) buffer ClusterCountBuffer
{
	uint count;
	uint workgroupX;
	uint workgroupY;
	uint workgroupZ;
};


layout(buffer_reference, std430) buffer MeshTaskBuffer
{ 
	MeshTaskCommand commands[];
};
	
layout(buffer_reference, std430) buffer VisibilityBuffer
{
	uint visible[];
};

layout(buffer_reference, std430) readonly buffer MeshletBuffer
{ 
	Meshlet meshlets[];
};


layout(push_constant) uniform constants
{
	mat4 view;
	vec4 frustumPlanes;
	
	ObjectBuffer objectBuffer;
	MeshletBuffer meshletBuffer;
	ClusterIndicesBuffer clusterIndicesBuffer;
	ClusterCountBuffer clusterCountBuffer; 
	CountBuffer countBuffer; 
	VisibilityBuffer meshletVisBuffer; // meshletVisibilityBuffer
	MeshTaskBuffer meshTaskBuffer;
	
	uint count;
	uint late;
	uint textureId;
	uint occlusionEnabled;
	
	float p00;
	float p11;
	float znear;
	float zfar;
	
	vec2 resolution;
	float textureLod;
	float lodDistanceFactor;
	uint lodEnabled;
	uint taskSubmit;
} pc;

layout(set = 0, binding = 0, r32f) uniform image2D allImages[];
layout(set = 1, binding = 0) uniform texture2D allTextures[];
layout(set = 2, binding = 0) uniform sampler samplers[];

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
// https://zeux.io/2023/01/12/approximate-projected-bounds/
bool projectSphere(vec3 c, float r, float znear, float P00, float P11, out vec4 aabb)
{
	if (c.z < r + znear)
		return false;

    vec3 cr = c * r;
    float czr2 = c.z * c.z - r * r;

    float vx = sqrt(c.x * c.x + czr2);
    float minx = (vx * c.x - cr.z) / (vx * c.z + cr.x);
    float maxx = (vx * c.x + cr.z) / (vx * c.z - cr.x);

    float vy = sqrt(c.y * c.y + czr2);
    float miny = (vy * c.y - cr.z) / (vy * c.z + cr.y);
    float maxy = (vy * c.y + cr.z) / (vy * c.z - cr.y);

    aabb = vec4(minx * P00, miny * P11, maxx * P00, maxy * P11);
    // clip space -> uv space
    aabb = aabb.xwzy * vec4(0.5f, -0.5f, 0.5f, -0.5f) + vec4(0.5f);

    return true;
}

bool frustumCulled(vec3 center, float radius)
{
	bool visible = true;
	
	// symmetrical sphere-plane distance test
	visible = visible && (center.z * pc.frustumPlanes.y - abs(center.x) * pc.frustumPlanes.x) >= -radius;
	visible = visible && (center.z * pc.frustumPlanes.w - abs(center.y) * pc.frustumPlanes.z) >= -radius;
	visible = visible && (center.z - radius <= -pc.znear) && (center.z + radius >= -pc.zfar);	
		
	return !visible;
}

bool occlusionCulled(vec3 center, float radius)
{
	vec4 aabb;
	
	if (projectSphere(vec3(center.x, center.y, -center.z), radius, pc.znear, pc.p00, pc.p11, aabb))
	{
		vec2 pixelSize = (aabb.zw - aabb.xy) * pc.resolution; 
		
		float max_dim = max(pixelSize.x, pixelSize.y);
		
		float mip = ceil(log2(max_dim));
		mip = min(mip, pc.textureLod); // TODO: PC
		
		float depth = textureLod(sampler2D(allTextures[pc.textureId], samplers[4]), (aabb.zw + aabb.xy) * 0.5, mip).r;
		
		float depthSphere = pc.znear / (-center.z - radius); 
		
		return depthSphere < depth; // reverse depth
	}
}

void main()
{
	uint id = gl_GlobalInvocationID.x;
	
	uint meshletOffset = pc.meshTaskBuffer.commands[id].meshletOffset;
	uint objectId = pc.meshTaskBuffer.commands[id].objectId;
	uint meshletVisibilityOffset = pc.meshTaskBuffer.commands[id].meshletVisibilityOffset;
	uint meshVisibility = pc.meshTaskBuffer.commands[id].meshVisibility;
	
	uint totalMeshlets = pc.countBuffer.count; 
	
	if (id < totalMeshlets)
	{
		bool late = pc.late == 1;
		bool visibleLastFrame = pc.meshletVisBuffer.visible[meshletVisibilityOffset] == 1;
		
		if (!late && !visibleLastFrame)
			return;
		
		bool skip = false;
		//if (late && meshVisibility == 1 && visibleLastFrame)
		if (late && visibleLastFrame) // meshVisibility redundant? uncomment for now
			skip = true;
			
		// reprocess all meshlets of visible meshes	
		Meshlet meshlet = pc.meshletBuffer.meshlets[meshletOffset];
		
		ObjectData obj = pc.objectBuffer.objects[objectId];
	
		vec3 center = vec3(pc.view * obj.worldMatrix * vec4(meshlet.center, 1.0));
		float radius = meshlet.radius;
		
		vec3 right = vec3(obj.worldMatrix[0]);
		vec3 up = vec3(obj.worldMatrix[1]);
		vec3 forward = vec3(obj.worldMatrix[2]);
		
		vec3 scale = vec3(length(right), length(up), length(forward));
		
		float maxScale = max(scale.z, max(scale.x, scale.y));
		radius = radius * maxScale;
		
		// frustum culling
		bool visible = !frustumCulled(center, radius);
		
		if (late && visible)
		{
			if (pc.occlusionEnabled == 1)
				visible = visible && !occlusionCulled(center, radius);
		}
		
		// render or not - both pass 1 & 2
		if (visible && !skip)
		{
			uint clusterIndex = atomicAdd(pc.clusterCountBuffer.workgroupX, 1);
			pc.clusterCountBuffer.workgroupY = 1;
			pc.clusterCountBuffer.workgroupZ = 1;
			
			pc.clusterIndicesBuffer.indices[clusterIndex] = id;
			
			pc.countBuffer.workgroupY = meshletVisibilityOffset;
		}
		
		if (late)
			pc.meshletVisBuffer.visible[meshletVisibilityOffset] = uint(visible); 
	}
}

// purpose of cluster submit
// does meshlets.mesh read from an instance-like buffer?