#version 460

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"
#include "buffer_references.glsl"
#include "util.glsl"
#include "prefix_sum.glsl"

layout (local_size_x = 256) in;

layout(push_constant) uniform constants
{
	mat4 view;
	vec4 frustum_planes;

	ObjectBuffer object_buffer;
	MeshBuffer mesh_buffer;
	MeshIndicesBuffer mesh_indices_buffer;
	DrawCommandsBuffer draw_buffer;
	DispatchBuffer dispatch_buffer;
	VisibilityBuffer mesh_visibility_buffer;
	PrefixSumBuffer prefix_sum_buffer;

	uint count;
	uint late;
	uint texture_id;
	uint occlusion_enabled;

	float p00;
	float p11;
	float near;
	float far; // this is draw distance

	vec2 resolution;
	float texture_lod;
	float lod_distance_factor;
	uint lod_enabled;
	uint task_submit;
	uint post_pass;
};

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
// https://zeux.io/2023/01/12/approximate-projected-bounds/
bool project_sphere(vec3 c, float r, float near, float p00, float p11, out vec4 aabb)
{
	if (c.z < r + near)
		return false;

    vec3 cr = c * r;
    float czr2 = c.z * c.z - r * r;

    float vx = sqrt(c.x * c.x + czr2);
    float minx = (vx * c.x - cr.z) / (vx * c.z + cr.x);
    float maxx = (vx * c.x + cr.z) / (vx * c.z - cr.x);

    float vy = sqrt(c.y * c.y + czr2);
    float miny = (vy * c.y - cr.z) / (vy * c.z + cr.y);
    float maxy = (vy * c.y + cr.z) / (vy * c.z - cr.y);

    aabb = vec4(minx * p00, miny * p11, maxx * p00, maxy * p11);
    // clip space -> uv space
    aabb = aabb.xwzy * vec4(0.5, -0.5, 0.5, -0.5) + vec4(0.5);

    return true;
}

bool frustum_culled(vec3 center, float radius)
{
	bool visible = true;

	// symmetrical sphere-plane distance test
	visible = visible && (center.z * frustum_planes.y - abs(center.x) * frustum_planes.x) >= -radius;
	visible = visible && (center.z * frustum_planes.w - abs(center.y) * frustum_planes.z) >= -radius;
	visible = visible && (center.z - radius <= -near) && (center.z + radius >= -far);

	return !visible;
}

bool occlusion_culled(vec3 center, float radius)
{
	vec4 aabb;

	if (project_sphere(vec3(center.x, center.y, -center.z), radius, near, p00, p11, aabb))
	{
		vec2 pixel_size = (aabb.zw - aabb.xy) * resolution;

		float max_dim = max(pixel_size.x, pixel_size.y);

		float mip = ceil(log2(max_dim));
		mip = min(mip, texture_lod);

		float depth = textureLod(sampler2D(textures[texture_id], samplers[DEPTH_REDUCTION_SAMPLER]), (aabb.zw + aabb.xy) * 0.5, mip).r;

		float depth_sphere = near / (-center.z - radius);

		return depth_sphere < depth; // reverse depth
	}
}

void main()
{
	uint global_id = gl_GlobalInvocationID.x;

	if (global_id >= count)
		return;

	uint id = mesh_indices_buffer.indices[global_id];

	bool late = late == 1;

	// TODO: mesh_visibility_buffer using 4 bytes instead of 1 bit for visibility
	// TODO: can potentially skip this for post_pass != 0 (masked, transparent)?
	bool visible_last_frame = mesh_visibility_buffer.visible[id] == 1;

	if (!late && !visible_last_frame)
		return;

	ObjectData obj = object_buffer.objects[id];

	uint mesh_id = obj.mesh_id;
	MeshData mesh = mesh_buffer.meshes[mesh_id];

	vec3 mpos = mesh.center;
	vec3 center = rotate_quat(mpos, obj.orientation) * obj.scale + obj.translation; // world space
	center = vec3(view * vec4(center, 1.0)); // view space

	float radius = mesh.radius;

    // non uniform scaling not support
	float max_scale = obj.scale;
	radius = radius * max_scale;

	bool visible = !frustum_culled(center, radius);
	bool should_draw = visible;

	if (late && visible)
	{
		if (occlusion_enabled == 1)
			visible = visible && !occlusion_culled(center, radius);
		should_draw = (task_submit == 0) ? visible && (!visible_last_frame || post_pass != 0) : visible; // TODO: verify we can remove postpass check here as we dispatch by geometry type?
	}

	if (should_draw)
	{

		uint index = 0;
		if (lod_enabled == 1) // TODO: move above into this block?
		{
			// automatic LOD selection - at distance d, how many world space units does each pixel cover?
			// is the absolute error computed (simplifyscale * result_error) less visible than error above? if so, move onto higher LOD
			float d = max(0.0, length(center) - radius);
			float e = d * lod_distance_factor / max_scale;

			for (uint i = 0; i < mesh.lod_count; i++)
			{
				index = e >= mesh.lods[i].error ? i : index;
			}
		}

		if (task_submit == 1)
		{
			uint meshlet_count = mesh.lods[index].meshlet_count;
			uint meshlet_offset = mesh.lods[index].meshlet_offset;

			uint count = atomicAdd(dispatch_buffer.workgroup_x, meshlet_count);

			prefix_sum_inclusive_append(prefix_sum_buffer, id, meshlet_count, meshlet_offset);

		}
		else
		{
			// TODO: currently, third pass for masked geometry is only culling for late==1. it is incremented in opaqueCount. make a proper distinction when we cull masked geometry in early and late?
			uint count = atomicAdd(draw_buffer.draws.opaque_count, 1);

			DrawCommand draw;
			draw.index_count = mesh.lods[index].count;
			draw.instance_count = 1;
			draw.first_index = mesh.lods[index].first_index;
			draw.vertex_offset = mesh.vertex_offset;
			draw.first_instance = id;

			draw_buffer.draws.commands[count] = draw;
		}
	}

	if (late)
		mesh_visibility_buffer.visible[id] = uint(visible);
}
