#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"
#include "buffer_references.glsl"

layout (local_size_x = 256) in;

layout(push_constant) uniform constants
{
	mat4 view;
	vec4 frustumPlanes;
	
	ObjectBuffer objectBuffer;
	MeshBuffer meshBuffer;
	IndicesBuffer indicesBuffer;
	DrawCommandsBuffer drawBuffer;
	DispatchBuffer dispatchBuffer;
	VisibilityBuffer visBuffer;
	MeshTaskBuffer meshTaskBuffer;
	
	uint count;
	uint late;
	uint textureId;
	uint occlusionEnabled;
	
	float p00;
	float p11;
	float znear;
	float zfar; // this is draw distance
	
	vec2 resolution;
	float textureLod;
	float lodDistanceFactor;
	uint lodEnabled;
	uint taskSubmit;
	uint postPass;
} pc;

// 2D Polyhedral Bounds of a Clipped, Perspective-Projected 3D Sphere. Michael Mara, Morgan McGuire. 2013
// https://zeux.io/2023/01/12/approximate-projected-bounds/
bool projectSphere(vec3 c, float r, float znear, float P00, float P11, out vec4 aabb)
{
	if (c.z < r + znear)
		return false;

    vec3 cr = c * r;
    float czr2 = c.z * c.z - r * r;

    float vx = sqrt(c.x * c.x + czr2);
    float minx = (vx * c.x - cr.z) / (vx * c.z + cr.x);
    float maxx = (vx * c.x + cr.z) / (vx * c.z - cr.x);

    float vy = sqrt(c.y * c.y + czr2);
    float miny = (vy * c.y - cr.z) / (vy * c.z + cr.y);
    float maxy = (vy * c.y + cr.z) / (vy * c.z - cr.y);

    aabb = vec4(minx * P00, miny * P11, maxx * P00, maxy * P11);
    // clip space -> uv space
    aabb = aabb.xwzy * vec4(0.5f, -0.5f, 0.5f, -0.5f) + vec4(0.5f);

    return true;
}

bool frustumCulled(vec3 center, float radius)
{
	bool visible = true;
	
	// symmetrical sphere-plane distance test
	visible = visible && (center.z * pc.frustumPlanes.y - abs(center.x) * pc.frustumPlanes.x) >= -radius;
	visible = visible && (center.z * pc.frustumPlanes.w - abs(center.y) * pc.frustumPlanes.z) >= -radius;
	visible = visible && (center.z - radius <= -pc.znear) && (center.z + radius >= -pc.zfar);	
		
	return !visible;
}

bool occlusionCulled(vec3 center, float radius)
{
	vec4 aabb;
	
	if (projectSphere(vec3(center.x, center.y, -center.z), radius, pc.znear, pc.p00, pc.p11, aabb))
	{
		vec2 pixelSize = (aabb.zw - aabb.xy) * pc.resolution; 
		
		float max_dim = max(pixelSize.x, pixelSize.y);
		
		float mip = ceil(log2(max_dim));
		mip = min(mip, pc.textureLod); // TODO: PC
		
		float depth = textureLod(sampler2D(textures[pc.textureId], samplers[DEPTH_REDUCTION_SAMPLER]), (aabb.zw + aabb.xy) * 0.5, mip).r;
		
		float depthSphere = pc.znear / (-center.z - radius); 
		
		return depthSphere < depth; // reverse depth
	}
}

void main()
{
	uint globalId = gl_GlobalInvocationID.x;
	
	if (globalId >= pc.count)
		return;
		
	uint id = pc.indicesBuffer.indices[globalId];
	
	bool late = pc.late == 1;
	
	// TODO: visBuffer using 4 bytes instead of 1 bit for visibility
	// TODO: can potentially skip this for pc.postPass != 0 (masked, transparent?)
	bool visibleLastFrame = pc.visBuffer.visible[id] == 1;
	
	if (!late && !visibleLastFrame)
		return;
		
	ObjectData obj = pc.objectBuffer.objects[id];

	// should no longer be necessary as we render by mask/opaque/transparent now
	// late check should be unnecessary, masked geometry will behave like a third pass after 2-pass cull
	//if (obj.postPass != pc.postPass) 
		//return;
		
	uint meshID = obj.meshID;
	MeshData mesh = pc.meshBuffer.meshes[meshID];

	vec3 center = vec3(pc.view * obj.worldMatrix * vec4(mesh.center, 1.0));
	float radius = mesh.radius;
	
	vec3 right = vec3(obj.worldMatrix[0]);
	vec3 up = vec3(obj.worldMatrix[1]);
	vec3 forward = vec3(obj.worldMatrix[2]);
	
	vec3 scale = vec3(length(right), length(up), length(forward));
	
	float maxScale = max(scale.z, max(scale.x, scale.y));
	radius = radius * maxScale;
	
	bool visible = !frustumCulled(center, radius);
	bool shouldDraw = visible;
	
	if (late && visible)
	{
		if (pc.occlusionEnabled == 1)
			visible = visible && !occlusionCulled(center, radius);
		shouldDraw = (pc.taskSubmit == 0) ? visible && (!visibleLastFrame || pc.postPass != 0) : visible;
	}
	
	if (shouldDraw)
	{
		// automatic LOD selection - at distance d, how many world space units does each pixel cover? 
		// is the absolute error computed (simplifyscale * result_error) less visible than error above? if so, move onto higher LOD
		float d = max(0.0, length(center) - radius);
		float e = d * pc.lodDistanceFactor / maxScale;
		
		uint index = 0;
		if (pc.lodEnabled == 1) // TODO: move above into this block?
		{
			for (uint i = 0; i < mesh.lodCount; i++)
			{
				index = e >= mesh.lods[i].error ? i : index;
			}
		}
		
		// TODO: inspired by https://github.com/expenses/lighthugger/blob/main/src/shaders/common/prefix_sum.glsl
		// - prefixSum buffer storing instanceId, inclusive sum of meshletCount, and another new variable to account for LOD offsets to correctly index into meshlet buffer
		// - dispatchBuffer needs to be handled in a new compute shader
		// - meshletBitOffset/meshletVisibilityOffset obsolete as we can look into object/instanceBuffer for buffer offset + local offset computed from prefixSum?
		// - so 4 uints down to 3 uints per meshtask, on top of 1 meshtask command PER mesh?
		// - meshtask buffer replaced by prefixSum buffer, and each entry maps to a single visible mesh, no longer ceil(meshlets/32) entries
		
		if (pc.taskSubmit == 1)
		{
			uint meshletCount = mesh.lods[index].meshletCount;
			uint meshletOffset = mesh.lods[index].meshletOffset;

			// experiment 32 meshlets per workgroup, each workgroup limited to meshlets from a single mesh
			uint tasks = (meshletCount + 31) / 32;
			uint count = atomicAdd(pc.dispatchBuffer.workgroupX, tasks); 
			pc.dispatchBuffer.workgroupY = 1;
			pc.dispatchBuffer.workgroupZ = 1;
			for (uint i = 0; i < tasks; i++)
			{
				pc.meshTaskBuffer.commands[count + i].meshletOffset = meshletOffset + i * 32;
				pc.meshTaskBuffer.commands[count + i].objectId = id;
				pc.meshTaskBuffer.commands[count + i].meshletVisibilityOffset = obj.meshletBitOffset + i * 32;
				pc.meshTaskBuffer.commands[count + i].meshletCount = min(32, meshletCount - i * 32);
			}
		}
		else
		{
			// TODO: currently, third pass for masked geometry is only culling for late==1. it is incremented in opaqueCount. make a proper distinction when we cull masked geometry in early and late?
			uint count = atomicAdd(pc.drawBuffer.draws[0].opaqueCount, 1);
			pc.drawBuffer.draws[0].commands[count].indexCount = mesh.lods[index].count;
			pc.drawBuffer.draws[0].commands[count].instanceCount = 1;
			pc.drawBuffer.draws[0].commands[count].firstIndex = mesh.lods[index].firstIndex;
			pc.drawBuffer.draws[0].commands[count].vertexOffset = mesh.vertexOffset;
			pc.drawBuffer.draws[0].commands[count].firstInstance = id;
		}
	}
	
	if (late)
		pc.visBuffer.visible[id] = uint(visible); 
}