#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"

layout (local_size_x = 32, local_size_y = 32) in;

const float PI = 3.14159265359;

layout (push_constant) uniform constants
{
	vec2 imageSize;
	uint texture_id;
	uint image_id;
	float roughness;
} pc;

float RadicalInverse_VdC(uint bits) 
{
    bits = (bits << 16u) | (bits >> 16u);
    bits = ((bits & 0x55555555u) << 1u) | ((bits & 0xAAAAAAAAu) >> 1u);
    bits = ((bits & 0x33333333u) << 2u) | ((bits & 0xCCCCCCCCu) >> 2u);
    bits = ((bits & 0x0F0F0F0Fu) << 4u) | ((bits & 0xF0F0F0F0u) >> 4u);
    bits = ((bits & 0x00FF00FFu) << 8u) | ((bits & 0xFF00FF00u) >> 8u);
    return float(bits) * 2.3283064365386963e-10; // / 0x100000000
}

vec2 Hammersley(uint i, uint N)
{
    return vec2(float(i)/float(N), RadicalInverse_VdC(i));
} 

vec3 ImportanceSampleGGX(vec2 Xi, vec3 N, float linearRoughness)
{
    float a = linearRoughness;
	
	// this mapping assumes we're restricting ourselves to an isotropic version of GGX, see https://bruop.github.io/ibl/
    float phi = 2.0 * PI * Xi.x;
    float cosTheta = sqrt((1.0 - Xi.y) / (1.0 + (a*a - 1.0) * Xi.y));
    float sinTheta = sqrt(1.0 - cosTheta*cosTheta);
	
    // from spherical coordinates to cartesian coordinates
    vec3 H = vec3(0.0);
    H.x = cos(phi) * sinTheta;
    H.y = sin(phi) * sinTheta;
    H.z = cosTheta;
	
    // from tangent-space vector to world-space sample vector
    vec3 up = abs(N.z) < 0.999 ? vec3(0.0, 0.0, 1.0) : vec3(1.0, 0.0, 0.0);
    vec3 tangent = normalize(cross(up, N));
    vec3 bitangent = cross(N, tangent);
	
    vec3 sampleVec = tangent * H.x + bitangent * H.y + N * H.z;
    return normalize(sampleVec);
}  

float D_GGX(float NdotH, float linearRoughness)
{
	float a = NdotH * linearRoughness;
	float k = linearRoughness / (1.0 - NdotH * NdotH + a * a);
	return k * k * (1.0 / PI);
}

void main()
{
	vec3 direction = vec3(0.0);

	vec2 texelCoord = vec2(gl_GlobalInvocationID.xy);
	ivec2 image_size = imageSize(images_array_rgba32f[pc.image_id]).xy;
	
	if (texelCoord.x >= image_size.x || texelCoord.y >= image_size.y)
		return;
		
	vec2 uv = (texelCoord + vec2(0.5)) / vec2(image_size);
	uv = uv * 2.0 - 1.0;
	
	float perceptualRoughness = pc.roughness;
	float envmapSize = float(textureSize(samplerCube(textures_cube[pc.texture_id], samplers[CUBE_SAMPLER]), 0).r);
	
	uint face = gl_WorkGroupID.z;
	
	switch (face)
	{
		case 0: direction = normalize(vec3(1.0, -uv.y, -uv.x)); break; // +X
		case 1: direction = normalize(vec3(-1.0, -uv.y, uv.x)); break; // -X
		case 2: direction = normalize(vec3(uv.x, 1.0, uv.y)); break; // +Y
		case 3: direction = normalize(vec3(uv.x, -1.0, -uv.y)); break; // -Y
		case 4: direction = normalize(vec3(uv.x, -uv.y, 1.0)); break; // +Z
		case 5: direction = normalize(vec3(-uv.x, -uv.y, -1.0)); break; // -Z
		default: direction = vec3(0.0); break; 
	}
	
	vec3 N = direction;
	vec3 V = N;
	float linearRoughness = perceptualRoughness * perceptualRoughness;

	uint sampleCount = 32;
	float totalWeight = 0.0;
	vec3 prefilteredColor = vec3(0.0);
	for (uint i = 0; i < sampleCount; i++)
	{
		vec2 Xi = Hammersley(i, sampleCount);
		vec3 H = ImportanceSampleGGX(Xi, N, linearRoughness); 
		vec3 L = normalize(2.0 * dot(V,H) * H - V);

		float NdotL = max(dot(N, L), 0.0);
		float NdotH = max(dot(N, H), 0.0);
		if (NdotL > 0.0)
		{
			// https://developer.nvidia.com/gpugems/gpugems3/part-iii-rendering/chapter-20-gpu-based-importance-sampling
			// https://chetanjags.wordpress.com/2015/08/26/image-based-lighting/
			float pdf = D_GGX(NdotH, linearRoughness) / 4.0 + 0.0001; // NdotH and VdotH (from Jacobian) cancel out
			float omegaS = 1.0 / (float(sampleCount) * pdf);  // solid angle of a sample
			float omegaP = 4.0 * PI / (6.0 * envmapSize * envmapSize); // solid angle of one pixel from cubemap/sphere
			float mipLevel = perceptualRoughness == 0.0 ? 0.0 : max(0.5 * log2(omegaS / omegaP) + 1.0, 0.0);
			
			prefilteredColor += textureLod(samplerCube(textures_cube[pc.texture_id], samplers[CUBE_SAMPLER]), L, mipLevel).rgb * NdotL;
			totalWeight += NdotL;
		}
	}

	prefilteredColor = prefilteredColor / totalWeight;
	
	imageStore(images_array_rgba32f[pc.image_id], ivec3(texelCoord, face), vec4(prefilteredColor, 1.0));
}