// References
// https://www.elopezr.com/temporal-aa-and-the-quest-for-the-holy-trail/
// https://alextardif.com/TAA.html
// https://github.com/playdeadgames/temporal/blob/master/Assets/Shaders/TemporalReprojection.shader
// https://advances.realtimerendering.com/s2014/#_HIGH-QUALITY_TEMPORAL_SUPERSAMPLING
// https://developer.download.nvidia.com/gameworks/events/GDC2016/msalvi_temporal_supersampling.pdf

// note: not optimized, targetting correctness

#version 460

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"
#include "buffer_references.glsl"

layout (local_size_x = 32, local_size_y = 32) in;

layout (push_constant) uniform constants
{
	vec2 screen_size;
	uint current_id;
	uint history_id;
	uint resolve_id;
	uint depth_id;
	uint velocity_id;
	uint variance_clipping;
	uint history_filter;
	uint local_filter; // unused
	uint ycocg;
	uint valid_history; // valid when first_frame==false
};

/*
// https://github.com/TheRealMJP/MSAAFilter/blob/master/MSAAFilter/Resolve.hlsl
float filter_cubic(float x, float B, float C)
{
    float y = 0.0f;
    float x2 = x * x;
    float x3 = x * x * x;
    if (x < 1)
        y = (12 - 9 * B - 6 * C) * x3 + (-18 + 12 * B + 6 * C) * x2 + (6 - 2 * B);
    else if (x <= 2)
        y = (-B - 6 * C) * x3 + (6 * B + 30 * C) * x2 + (-12 * B - 48 * C) * x + (8 * B + 24 * C);

    return y / 6.0f;
}

float filter_mitchell(float value)
{
	return filter_cubic(value, 1.0 / 3.0, 1.0 / 3.0);
}
*/

// https://gpuopen.com/learn/optimized-reversible-tonemapper-for-resolve/
vec3 tonemap(vec3 c)
{
    float w = max(c.x, max(c.y, c.z));
    return c / (1.0 + w);
}

vec3 reverse_tonemap(vec3 c)
{
    float w = max(c.x, max(c.y, c.z));
    return c / (1.0 - w);
}

vec3 rgb_to_ycocg(vec3 c)
{
    float y = c.x / 4.0 + c.y / 2.0 + c.z / 4.0;
    float co = c.x / 2.0 - c.z / 2.0;
    float cg = -c.x / 4.0 + c.y / 2.0 - c.z / 4.0;

    return vec3(y, co, cg);
}

vec3 ycocg_to_rgb(vec3 c)
{
    float tmp = c.x - c.z;
    float r = tmp + c.y;
    float g = c.r + c.z;
    float b = tmp - c.y;

    return clamp(vec3(r,g,b), vec3(0.0), vec3(1.0));
}

vec3 sample_color(uint texture_index, uint sampler_index, vec2 uv)
{
    vec3 color = tonemap(texture(sampler2D(textures[texture_index], samplers[sampler_index]), uv).xyz);

    if (ycocg == 1)
        color = rgb_to_ycocg(color);

    return color;
}

// 9 tap exploiting bilinear filtering: https://gist.github.com/TheRealMJP/c83b8c0f46b63f3a88a5986f4fa982b1
// for more details: http://vec3.ca/bicubic-filtering-in-fewer-taps/
vec3 sample_texture_catmull_rom(vec2 uv, uint texture_index, vec2 resolution)
{
    // We're going to sample a a 4x4 grid of texels surrounding the target UV coordinate. We'll do this by rounding
    // down the sample location to get the exact center of our "starting" texel. The starting texel will be at
    // location [1, 1] in the grid, where [0, 0] is the top left corner.
    vec2 sample_position = uv * resolution;
    vec2 tex_pos_1 = floor(sample_position - 0.5) + 0.5;

    // Compute the fractional offset from our starting texel to our original sample location, which we'll
    // feed into the Catmull-Rom spline function to get our filter weights.
    vec2 f = sample_position - tex_pos_1;

    // Compute the Catmull-Rom weights using the fractional offset that we calculated earlier.
    // These equations are pre-expanded based on our knowledge of where the texels will be located,
    // which lets us avoid having to evaluate a piece-wise function.
    vec2 w0 = f * (-0.5 + f * (1.0 - 0.5 * f));
    vec2 w1 = 1.0 + f * f * (-2.5 + 1.5 * f);
    vec2 w2 = f * (0.5 + f * (2.0 - 1.5 * f));
    vec2 w3 = f * f * (-0.5 + 0.5 * f);

    // Work out weighting factors and sampling offsets that will let us use bilinear filtering to
    // simultaneously evaluate the middle 2 samples from the 4x4 grid.
    vec2 w12 = w1 + w2;
    vec2 offset_12 = w2 / w12;

    // Compute the final UV coordinates we'll use for sampling the texture
    vec2 tex_pos_0 = tex_pos_1 - 1;
    vec2 tex_pos_3 = tex_pos_1 + 2;
    vec2 tex_pos_12 = tex_pos_1 + offset_12;

    tex_pos_0 /= resolution;
    tex_pos_3 /= resolution;
    tex_pos_12 /= resolution;

    vec3 result = vec3(0);
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_0.x, tex_pos_0.y)).rgb) * w0.x * w0.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_12.x, tex_pos_0.y)).rgb) * w12.x * w0.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_3.x, tex_pos_0.y)).rgb) * w3.x * w0.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_0.x, tex_pos_12.y)).rgb) * w0.x * w12.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_12.x, tex_pos_12.y)).rgb) * w12.x * w12.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_3.x, tex_pos_12.y)).rgb) * w3.x * w12.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_0.x, tex_pos_3.y)).rgb) * w0.x * w3.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_12.x, tex_pos_3.y)).rgb) * w12.x * w3.y;
    result += tonemap(texture(sampler2D(textures[texture_index], samplers[LINEAR_CLAMP_SAMPLER]), vec2(tex_pos_3.x, tex_pos_3.y)).rgb) * w3.x * w3.y;

    if (ycocg == 1)
        result = rgb_to_ycocg(result);

    return result;
}

// Optimized ver from Inside/playdeadgames
vec4 clip_aabb(vec3 aabb_min, vec3 aabb_max, vec4 q, float average_alpha)
{
	// note: only clips towards aabb center (but fast!)
	vec3 p_clip = 0.5 * (aabb_max + aabb_min);
	vec3 e_clip = 0.5 * (aabb_max - aabb_min) + 0.00000001;

	vec4 v_clip = q - vec4(p_clip, average_alpha);
	vec3 v_unit = v_clip.xyz / e_clip;
	vec3 a_unit = abs(v_unit);
	float ma_unit = max(a_unit.x, max(a_unit.y, a_unit.z));

	if (ma_unit > 1.0)
		return vec4(p_clip, average_alpha) + v_clip / ma_unit;
	else
		return q; // point inside aabb
}

void main()
{
    ivec2 texel_coord = ivec2(gl_GlobalInvocationID.xy);

    if (texel_coord.x >= screen_size.x || texel_coord.y >= screen_size.y)
        return;

	vec2 uv = vec2(texel_coord) + vec2(0.5);
	uv /= screen_size;

	if (valid_history == 0)
	{
	    vec3 history_color = sample_color(current_id, NEAREST_SAMPLER, uv);
		imageStore(images_rgba32f[resolve_id], texel_coord, vec4(history_color, 1.0));
		return;
	}

	// depth dilation
	float closest_depth = 0.0;
	vec2 closest_uv_offset;
	for (int x = -1; x <= 1; x++)
	{
		for (int y = -1; y <= 1; y++)
		{
			vec2 uv_offset = vec2(x, y) / screen_size;
			float neighbour_depth = texture(sampler2D(textures[depth_id], samplers[NEAREST_SAMPLER]), uv + uv_offset).r;
			if (neighbour_depth > closest_depth)
			{
				closest_depth = neighbour_depth;
				closest_uv_offset = uv_offset;
			}
		}
	}

	vec2 velocity_uv = texture(sampler2D(textures[velocity_id], samplers[NEAREST_SAMPLER]), uv + closest_uv_offset).rg;

	// neighbourhood sampling
	// alternative: blend this with a 5 taps '+' pattern per Karis UE4
	// TODO: ignore or accumulate clamped edges for variance clipping?
	vec3 ctl = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2(-1, 1) / screen_size));
	vec3 ctc = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2( 0, 1) / screen_size));
	vec3 ctr = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2( 1, 1) / screen_size));
	vec3 cml = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2(-1, 0) / screen_size));
	vec3 cmc = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2( 0, 0) / screen_size));
	vec3 cmr = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2( 1, 0) / screen_size));
	vec3 cbl = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2(-1,-1) / screen_size));
	vec3 cbc = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2( 0,-1) / screen_size));
	vec3 cbr = sample_color(current_id, NEAREST_SAMPLER, uv + (vec2( 1,-1) / screen_size));
	vec3 min_color = vec3(99999.0);
	vec3 max_color = vec3(-99999.0);
	min_color = min(ctl, min(ctc, min(ctr, min(cml, min(cmc, min(cmr, min(cbl, min(cbc, cbr))))))));
	max_color = max(ctl, max(ctc, max(ctr, max(cml, max(cmc, max(cmr, max(cbl, max(cbc, cbr))))))));

	// alternative: blackman, mitchell filter or average/weighted neighbourhood?
    vec3 current_color = cmc;

	// alternative: catmull 5-taps from COD?
	vec2 reprojected_uv = uv - velocity_uv;
	vec3 history_color;
	if (history_filter == 1)
		history_color = sample_texture_catmull_rom(reprojected_uv, history_id, screen_size);
	else
		history_color = sample_color(history_id, LINEAR_CLAMP_SAMPLER, reprojected_uv);

	// https://developer.download.nvidia.com/gameworks/events/GDC2016/msalvi_temporal_supersampling.pdf
	vec3 history_color_clamped;
	if (variance_clipping == 1)
	{
		vec3 m1 = ctl + ctc + ctr + cml + cmc + cmr + cbl + cbc + cbr;
		vec3 m2 = ctl * ctl + ctc * ctc + ctr * ctr + cml * cml + cmc * cmc + cmr * cmr + cbl * cbl + cbc * cbc + cbr * cbr;

		float rcp_samples = 1.0 / 9.0;
		// large gamma - temporally stable results at the cost of increased ghosting; small gamma - lose ability to integrate data over time
		float gamma = 1.0;
		vec3 mu = m1 * rcp_samples;
		vec3 sigma = sqrt(abs((m2 * rcp_samples) - (mu * mu)));
		vec3 minc = mu - gamma * sigma;
		vec3 maxc = mu + gamma * sigma;
		history_color_clamped = clip_aabb(minc, maxc, vec4(clamp(history_color, min_color, max_color), 1.0), 1.0).xyz;
	}
	else
	{
		history_color_clamped = clamp(history_color, min_color, max_color);
	}

	float blend_factor = 0.1;

	vec3 final_color = history_color_clamped + (current_color - history_color) * blend_factor;

	if (ycocg == 1)
	    final_color = ycocg_to_rgb(final_color);

	final_color = reverse_tonemap(final_color);

	// TODO: we can optimize by storing tonemapped value for next frame's history, skipping tonemapping for reprojected colors
	// but this is an inconvenience for experimenting with other post-fx for now, so we store reverse tonemapped values
	imageStore(images_rgba32f[resolve_id], texel_coord, vec4(final_color, 1.0));
}
