#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

#include "mesh.glsl"
#include "samplers.glsl"
#include "scene.glsl"

layout (local_size_x = 256) in;

layout(buffer_reference, std430) readonly buffer ObjectBuffer
{ 
	ObjectData objects[];
};

layout(buffer_reference, std430) readonly buffer MeshBuffer
{ 
	MeshData meshes[];
};

layout(buffer_reference, std430) readonly buffer IndicesBuffer
{ 
	uint indices[];
};

struct DrawCommands
{
	uint opaqueCount;
	uint alphaClipCount;
	DrawCommand commands[200000];
};

layout(buffer_reference, std430) buffer DrawCommandsBuffer
{ 
	DrawCommands draws[4];
};

layout(buffer_reference, std430) buffer DispatchBuffer
{
	uint workgroupX;
	uint workgroupY;
	uint workgroupZ;
};

layout(buffer_reference, std430) buffer MeshTaskBuffer
{ 
	MeshTaskCommand commands[];
};
	
layout(buffer_reference, std430) buffer VisibilityBuffer
{
	uint visible[];
};

layout(push_constant) uniform constants
{
	mat4 view;
	vec4 frustumPlanes;
	
	ObjectBuffer objectBuffer;
	MeshBuffer meshBuffer;
	IndicesBuffer indicesBuffer;
	DrawCommandsBuffer drawBuffer;
	DispatchBuffer dispatchBuffer;
	VisibilityBuffer visBuffer;
	MeshTaskBuffer meshTaskBuffer;
	
	uint count;
	uint late;
	uint textureId;
	uint occlusionEnabled;
	
	float p00;
	float p11;
	float znear;
	float zfar; // this is draw distance
	
	vec2 resolution;
	float textureLod;
	float lodDistanceFactor;
	uint lodEnabled;
	uint taskSubmit;
	uint postPass;
} pc;

//layout(set = 0, binding = 0, r32f) uniform image2D allImages[];
//layout(set = 1, binding = 0) uniform texture2D allTextures[];
//layout(set = 2, binding = 0) uniform sampler samplers[];

bool frustumCulled(vec3 center, float radius)
{
	bool visible = true;
	
	// symmetrical sphere-plane distance test
	visible = visible && (-abs(center.x) + sceneData.shadowWidth) >= -radius; 
	visible = visible && (-abs(center.y) + sceneData.shadowWidth) >= -radius; 
	visible = visible && (center.z - radius <= -pc.znear) && (center.z + radius >= -pc.zfar);	
		
	return !visible;
}

void main()
{
	uint globalId = gl_GlobalInvocationID.x;
	
	if (globalId >= pc.count)
		return;
		
	uint id = pc.indicesBuffer.indices[globalId];
	
	ObjectData obj = pc.objectBuffer.objects[id];
	uint meshID = obj.meshID;
	MeshData mesh = pc.meshBuffer.meshes[meshID];
	
	bool alphaClip = obj.postPass != 0;
	
	vec3 center = vec3(sceneData.shadowView * obj.worldMatrix * vec4(mesh.center, 1.0)); // USE CASCADE VIEW MATRIX
	float radius = mesh.radius;
	
	vec3 right = vec3(obj.worldMatrix[0]);
	vec3 up = vec3(obj.worldMatrix[1]);
	vec3 forward = vec3(obj.worldMatrix[2]);
	
	vec3 scale = vec3(length(right), length(up), length(forward));
	
	float maxScale = max(scale.z, max(scale.x, scale.y));
	radius = radius * maxScale;
	
	bool visible = !frustumCulled(center, radius);
	
	if (visible)
	{
		uint count = alphaClip ? atomicAdd(pc.drawBuffer.draws[0].alphaClipCount, 1) : atomicAdd(pc.drawBuffer.draws[0].opaqueCount, 1);
		count = alphaClip ? count + 200000 : count;
		pc.drawBuffer.draws[0].commands[count].indexCount = mesh.lods[0].count;           // FIX LOD
		pc.drawBuffer.draws[0].commands[count].instanceCount = 1;
		pc.drawBuffer.draws[0].commands[count].firstIndex = mesh.lods[0].firstIndex;
		pc.drawBuffer.draws[0].commands[count].vertexOffset = mesh.vertexOffset;
		pc.drawBuffer.draws[0].commands[count].firstInstance = id;
	}
}