#version 450

#extension GL_GOOGLE_include_directive : require

#define SHADOW_CULL

#include "bindings.glsl"
#include "buffer_references.glsl"
#include "util.glsl"

layout (local_size_x = 256) in;

layout(push_constant) uniform constants
{
	ObjectBuffer object_buffer; 
	MeshBuffer mesh_buffer; 
	MeshIndicesBuffer mesh_indices_buffer; 
	ShadowDrawCommandsBuffer draw_buffer;
	uint count; 
	uint lod_enabled;
	uint map;
};

bool partially_inside_cascade(vec3 center, uint cascade, float radius, float cascade_radius)
{
	bool visible = true;
	
	visible = visible && (-abs(center.x) + cascade_radius) >= -radius; 
	visible = visible && (-abs(center.y) + cascade_radius) >= -radius; 
	visible = visible && (center.z + radius >= (-2.0 * cascade_radius));// && (center.z - radius <= 0.0);	// disable near plane check for pancaking
		
	return visible;
}

// idea from: https://github.com/expenses/lighthugger/blob/9d6c46b3e339e9673b69b7d9933d6a439051232c/src/shaders/cull_instances.comp
bool completely_inside_cascade(vec3 world_pos, uint cascade_index, float radius, float cascade_radius)
{
    // view space center
    vec3 center = vec3(uniforms.shadow_views[cascade_index] * vec4(world_pos, 1.0)); // light space

	bool visible = true;
	
	visible = visible && (-abs(center.x) + cascade_radius) >= radius; 
	visible = visible && (-abs(center.y) + cascade_radius) >= radius; 
	visible = visible && (center.z - radius >= (-2.0 * cascade_radius));// && (center.z + radius <= 0.0);	// disable near plane check for pancaking
		
	return visible;
}

const int CASCADE_COUNT = 4;

void main()
{
	uint global_id = gl_GlobalInvocationID.x;
	
	if (global_id >= count)
		return;
		
	uint id = mesh_indices_buffer.indices[global_id];
	
	ObjectData obj = object_buffer.objects[id];
	uint mesh_id = obj.mesh_id;
	MeshData mesh = mesh_buffer.meshes[mesh_id];
	
	bool alpha_clip = obj.post_pass != 0;
	
	float radius = mesh.radius;
	
	// non uniform scaling not supported
	float max_scale = obj.scale;
	radius = radius * max_scale;
	
	// TODO: remove the loop and split this into more threads
	//bool early_out = false;
	float last_cascade_radius;
	//for (int cascade_index = 0; cascade_index < CASCADE_COUNT && !early_out; cascade_index++)
	for (int cascade_index = 0; cascade_index < CASCADE_COUNT; cascade_index++)
	{
		float cascade_radius = uniforms.shadow_widths[cascade_index];
		
		vec3 mpos = mesh.center;
		vec3 center = rotate_quat(mpos, obj.orientation) * obj.scale + obj.translation; // world space
		center = vec3(uniforms.shadow_views[cascade_index] * vec4(center, 1.0)); // light space
		
		if (!partially_inside_cascade(center, cascade_index, radius, cascade_radius))
            continue;
		
		// https://learn.microsoft.com/en-us/windows/win32/dxtecharts/cascaded-shadow-maps
		// this optimization complements map-based selection and is incompatible with interval-based map selection
		// comment to use interval-based map selection
		if (map == 1)
		{
		    //if (cascade_index != 0 && completely_inside_cascade(mpos, cascade_index - 1, radius, last_cascade_radius))
			    //early_out = true;

        }

		// TODO: verify that below is ok to go after completely_inside_cascade check
		uint lod_index = 0;
		if (lod_enabled == 1) 
		{
			// automatic LOD selection - at distance d, how many world space units does each pixel cover? 
			// is the absolute error computed (simplifyscale * result_error) less visible than error above? if so, move onto higher LOD
			float d = max(0.0, length(center) - radius);
			float lod_distance_factor = cascade_radius / 4096.0; // TODO: hardcoded; consider moving to PC to account for varying cascade resolution in the future
			float e = lod_distance_factor / max_scale;

			for (uint i = 0; i < mesh.lod_count; i++)
			{
				lod_index = e >= mesh.lods[i].error ? i : lod_index;
			}
		}
		
		uint count = alpha_clip ? atomicAdd(draw_buffer.draws[cascade_index].alpha_clip_count, 1) : atomicAdd(draw_buffer.draws[cascade_index].opaque_count, 1);
		uint index = alpha_clip ? count + 200000 : count;
		draw_buffer.draws[cascade_index].commands[index].index_count = mesh.lods[lod_index].count; 
		draw_buffer.draws[cascade_index].commands[index].instance_count = 1;
		draw_buffer.draws[cascade_index].commands[index].first_index = mesh.lods[lod_index].first_index;
		draw_buffer.draws[cascade_index].commands[index].vertex_offset = mesh.vertex_offset;
		draw_buffer.draws[cascade_index].commands[index].first_instance = id;

		last_cascade_radius = cascade_radius;
	}
}