#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"
#include "buffer_references.glsl"

layout (local_size_x = 256) in;

layout(push_constant) uniform constants
{
	ObjectBuffer objectBuffer; 
	MeshBuffer meshBuffer; 
	IndicesBuffer indicesBuffer; 
	DrawCommandsBuffer drawBuffer; 
	uint count; 
	uint lodEnabled;
} pc;

bool partiallyInsideCascade(vec3 center, uint cascade, float radius, float shadowRadius)
{
	bool visible = true;
	
	visible = visible && (-abs(center.x) + shadowRadius) >= -radius; 
	visible = visible && (-abs(center.y) + shadowRadius) >= -radius; 
	visible = visible && (center.z + radius >= (-2.0 * shadowRadius));// && (center.z - radius <= 0.0);	// disable near plane check for pancaking
		
	return visible;
}

bool completelyInsideCascade(vec3 center, uint cascade, float radius, float shadowRadius)
{
	bool visible = true;
	
	visible = visible && (-abs(center.x) + shadowRadius) >= radius; 
	visible = visible && (-abs(center.y) + shadowRadius) >= radius; 
	visible = visible && (center.z - radius >= (-2.0 * shadowRadius));// && (center.z + radius <= 0.0);	// disable near plane check for pancaking
		
	return visible;
}

const int CASCADE_COUNT = 4;

void main()
{
	uint globalId = gl_GlobalInvocationID.x;
	
	if (globalId >= pc.count)
		return;
		
	uint id = pc.indicesBuffer.indices[globalId];
	
	ObjectData obj = pc.objectBuffer.objects[id];
	uint meshID = obj.meshID;
	MeshData mesh = pc.meshBuffer.meshes[meshID];
	
	bool alphaClip = obj.postPass != 0;
	
	float radius = mesh.radius;
	
	vec3 right = vec3(obj.worldMatrix[0]);
	vec3 up = vec3(obj.worldMatrix[1]);
	vec3 forward = vec3(obj.worldMatrix[2]);
	
	vec3 scale = vec3(length(right), length(up), length(forward));
	
	float maxScale = max(scale.z, max(scale.x, scale.y));
	radius = radius * maxScale;
	
	for (int cascadeIdx = 0; cascadeIdx < CASCADE_COUNT; cascadeIdx++) 
	{
		float shadowRadius = sceneData.shadowWidths[cascadeIdx];
		vec3 center = vec3(sceneData.shadowViews[cascadeIdx] * obj.worldMatrix * vec4(mesh.center, 1.0));
		if (!partiallyInsideCascade(center, cascadeIdx, radius, shadowRadius))
			continue;
		
		// https://learn.microsoft.com/en-us/windows/win32/dxtecharts/cascaded-shadow-maps
		// this optimization complements map-based selection and is incompatible with interval-based map selection
		// disable to use interval-based map selection
		//if (cascadeIdx != 0 && completelyInsideCascade(center, cascadeIdx - 1, radius, shadowRadius))
		//	break;
		
		// TODO: verify that below is ok to go after completelyInsideCascade check
		// TODO: profile shadow LODs 
		uint index = 0;
		if (pc.lodEnabled == 1) 
		{
			// automatic LOD selection - at distance d, how many world space units does each pixel cover? 
			// is the absolute error computed (simplifyscale * result_error) less visible than error above? if so, move onto higher LOD
			float d = max(0.0, length(center) - radius);
			float lodDistanceFactor = shadowRadius / 4096.0; // TODO: seems to work ok - remove hardcoded value
			float e = lodDistanceFactor / maxScale;

			for (uint i = 0; i < mesh.lodCount; i++)
			{
				index = e >= mesh.lods[i].error ? i : index;
			}
		}
		
		uint count = alphaClip ? atomicAdd(pc.drawBuffer.draws[cascadeIdx].alphaClipCount, 1) : atomicAdd(pc.drawBuffer.draws[cascadeIdx].opaqueCount, 1);
		count = alphaClip ? count + 200000 : count;
		pc.drawBuffer.draws[cascadeIdx].commands[count].indexCount = mesh.lods[index].count; // TODO: LODS still unaccounted for
		pc.drawBuffer.draws[cascadeIdx].commands[count].instanceCount = 1;
		pc.drawBuffer.draws[cascadeIdx].commands[count].firstIndex = mesh.lods[index].firstIndex;
		pc.drawBuffer.draws[cascadeIdx].commands[count].vertexOffset = mesh.vertexOffset;
		pc.drawBuffer.draws[cascadeIdx].commands[count].firstInstance = id;
	}
}