// yoinked from: https://github.com/GPUOpen-Effects/FidelityFX-SPD/blob/master/ffx-spd/ffx_spd.h
// neat visualization: https://github.com/Goshido/android-vulkan/blob/master/docs/spd-algorithm.md
// may be interesting in the future: https://github.com/Themaister/Granite/blob/master/assets/shaders/post/hiz.comp

// Limitations:
// - Strictly PoT only
// - No texture array/cubemap support for now
//
// Instead of padding depth buffer to multiple of 64 or PoT, we lie to the shader that the depth buffer's size is PoT rounded up.
// When building mip 0, uv is remapped; instead of downsampling 2x2 in 2 texels increments (of the actual depth buffer's dimensions), its stepping in 1.x texel increments
// A small % of texels will be resampled for neighbouring 2x2 reductions, similar to our previous multi-pass hi-z shader. (Is this more conservative?)
// The step size between SPD and multi-pass is slightly different but still under step size of 2 so expect different occlusion culling numbers.
//
// Tried padding to next PoT with far plane depth, but for stress test scene lots of objects were not culled (~1ms difference).
// UV was remapped when sampling hi-z so we don't touch the padded data. Can't rule out that uv was remapped without errors.
// Best guess is padded values at the edges are still interfering with culling despite UV remapping.
// Renderdoc showed massive overdraw on the horizontal and vertical edges where padded data lived.
// Yet to try padding with clamped (actual) depth values instead of far plane depth.

#version 460

#extension GL_GOOGLE_include_directive : require
#extension GL_KHR_shader_subgroup_quad : require

#include "bindings.glsl"
#include "buffer_references.glsl"

layout (local_size_x = 256) in;

layout(set = 1, binding = 0, r32f) uniform coherent image2D images_r32f_coherent[];

layout(push_constant) uniform constants
{
    SpdCounterBuffer spd_counter_buffer;
	vec2 rcp_resolution; // resolution of src image, not mip 0
    uint mips;
	uint num_wgs;
	uint src_id; // texture to sample
	uint dst_id; // image to write to, offset accordingly!
	uint sampler_id;
	// uint wg_offset; // note: for subregion downsampling, not implemented for now
} pc;

shared float shared_intermediate[16][16];
shared uint spd_counter;

uint ABfe(uint src, uint off, uint bits)
{
    return bitfieldExtract(src, int(off), int(bits));
}

uint ABfiM(uint src, uint ins, uint bits)
{
    return bitfieldInsert(src, ins, 0, int(bits));
}

//  LANE TO 8x8 MAPPING
//  ===================
//  00 01 08 09 10 11 18 19
//  02 03 0a 0b 12 13 1a 1b
//  04 05 0c 0d 14 15 1c 1d
//  06 07 0e 0f 16 17 1e 1f
//  20 21 28 29 30 31 38 39
//  22 23 2a 2b 32 33 3a 3b
//  24 25 2c 2d 34 35 3c 3d
//  26 27 2e 2f 36 37 3e 3f
uvec2 ARmpRed8x8(uint a)
{
    return uvec2(ABfiM(ABfe(a, 2u, 3u), a, 1u), ABfiM(ABfe(a, 3u, 3u), ABfe(a, 1u, 2u), 2u));
}

float sample_texture(uint texture_id, uint sampler_id, vec2 uv, uint slice)
{
    return texture(sampler2D(textures[texture_id], samplers[sampler_id]), uv).r;
}

void spd_store_coherent(ivec2 coords, float value, uint slice)
{
    imageStore(images_r32f_coherent[pc.dst_id + 5], coords, vec4(value.r));
}

void spd_store(ivec2 coords, float value, uint mip, uint slice)
{
    imageStore(images_r32f[pc.dst_id + mip], coords, vec4(value));
}

void spd_store_intermediate(uint x, uint y, float value)
{
    shared_intermediate[x][y] = value;
}

// switch to this when we want min and max depth
float spd_load(ivec2 coords, uint mip, uint slice)
{
    return imageLoad(images_r32f[pc.dst_id + mip], coords).r;
}

float spd_load_intermediate(uint x, uint y)
{
    return shared_intermediate[x][y];
}

float spd_reduce_4(float v0, float v1, float v2, float v3)
{
    return min(v0, min(v1, min(v2, v3)));
}

float spd_reduce_quad(float v)
{
    float v0 = v;
    float v1 = subgroupQuadSwapHorizontal(v);
    float v2 = subgroupQuadSwapVertical(v);
    float v3 = subgroupQuadSwapDiagonal(v);

    return spd_reduce_4(v0, v1, v2, v3);
}

float spd_reduce_coherent_load(ivec2 base, uint slice)
{
    uint idx = pc.dst_id + 5;

    float v0 = imageLoad(images_r32f_coherent[idx], base).r;
    float v1 = imageLoad(images_r32f_coherent[idx], base + ivec2(0, 1)).r;
    float v2 = imageLoad(images_r32f_coherent[idx], base + ivec2(1, 0)).r;
    float v3 = imageLoad(images_r32f_coherent[idx], base + ivec2(1, 1)).r;

    return spd_reduce_4(v0, v1, v2, v3);
}

void spd_downsample_mips_0_1(uint x, uint y, uvec2 wg_id, uint local_id, uint mips, uint slice)
{
    float v[4];

    ivec2 tex = ivec2(wg_id * 64) + ivec2(x * 2, y * 2);
    vec2 uv = (vec2(tex) + vec2(0.5)) * pc.rcp_resolution;
    ivec2 pix = ivec2(wg_id * 32) + ivec2(x, y);
    v[0] = sample_texture(pc.src_id, pc.sampler_id, uv, 0);
    spd_store(pix, v[0], 0, slice);

    tex = ivec2(wg_id * 64) + ivec2(x * 2 + 32, y * 2);
    uv = (vec2(tex) + vec2(0.5)) * pc.rcp_resolution;
    pix = ivec2(wg_id * 32) + ivec2(x + 16, y);
    v[1] = sample_texture(pc.src_id, pc.sampler_id, uv, 0);
    spd_store(pix, v[1], 0, slice);

    tex = ivec2(wg_id * 64) + ivec2(x * 2, y * 2 + 32);
    uv = (vec2(tex) + vec2(0.5)) * pc.rcp_resolution;
    pix = ivec2(wg_id * 32) + ivec2(x, y + 16);
    v[2] = sample_texture(pc.src_id, pc.sampler_id, uv, 0);
    spd_store(pix, v[2], 0, slice);

    tex = ivec2(wg_id * 64) + ivec2(x * 2 + 32, y * 2 + 32);
    uv = (vec2(tex) + vec2(0.5)) * pc.rcp_resolution;
    pix = ivec2(wg_id * 32) + ivec2(x + 16, y + 16);
    v[3] = sample_texture(pc.src_id, pc.sampler_id, uv, 0);
    spd_store(pix, v[3], 0, slice);

    if (mips <= 1)
        return;

    v[0] = spd_reduce_quad(v[0]);
    v[1] = spd_reduce_quad(v[1]);
    v[2] = spd_reduce_quad(v[2]);
    v[3] = spd_reduce_quad(v[3]);

    if ((local_id % 4) == 0)
    {
        pix = ivec2(wg_id) * 16 + ivec2(x / 2, y / 2);
        spd_store(pix, v[0], 1, slice);
        spd_store_intermediate(x / 2, y / 2, v[0]);

        pix = ivec2(wg_id) * 16 + ivec2(x / 2 + 8, y / 2);
        spd_store(pix, v[1], 1, slice);
        spd_store_intermediate(x / 2 + 8, y / 2, v[1]);

        pix = ivec2(wg_id) * 16 + ivec2(x / 2, y / 2 + 8);
        spd_store(pix, v[2], 1, slice);
        spd_store_intermediate(x / 2, y / 2 + 8, v[2]);

        pix = ivec2(wg_id) * 16 + ivec2(x / 2 + 8, y / 2 + 8);
        spd_store(pix, v[3], 1, slice);
        spd_store_intermediate(x / 2 + 8, y / 2 + 8, v[3]);
    }
}

void spd_downsample_mip_2(uint x, uint y, uvec2 wg_id, uint local_id, uint mip, uint slice)
{
    float v = spd_load_intermediate(x, y);
    v = spd_reduce_quad(v);

    if (local_id % 4 == 0)
    {
        spd_store(ivec2(wg_id * 8) + ivec2(x / 2, y / 2), v, mip, slice);
        spd_store_intermediate(x + (y / 2) % 2, y, v);
    }
}

void spd_downsample_mip_3(uint x, uint y, uvec2 wg_id, uint local_id, uint mip, uint slice)
{
    if (local_id < 64)
    {
        float v = spd_load_intermediate(x * 2 + y % 2, y * 2);
        v = spd_reduce_quad(v);

        if (local_id % 4 == 0)
        {
            spd_store(ivec2(wg_id * 4) + ivec2(x / 2, y / 2), v, mip, slice);
            spd_store_intermediate(x * 2 + y / 2, y * 2, v);
        }
    }
}

void spd_downsample_mip_4(uint x, uint y, uvec2 wg_id, uint local_id, uint mip, uint slice)
{
    if (local_id < 16)
    {
        float v = spd_load_intermediate(x * 4 + y, y * 4);
        v = spd_reduce_quad(v);

        if (local_id % 4 == 0)
        {
            spd_store(ivec2(wg_id * 2) + ivec2(x / 2, y / 2), v, mip, slice);
            spd_store_intermediate(x / 2 + y, 0, v);
        }
    }
}

void spd_downsample_mip_5(uvec2 wg_id, uint local_id, uint mip, uint slice)
{
    if (local_id < 4)
    {
        float v = spd_load_intermediate(local_id, 0);
        v = spd_reduce_quad(v);

        if (local_id % 4 == 0)
        {
            if (mip == 5)
                spd_store_coherent(ivec2(wg_id), v, slice);
            else
                spd_store(ivec2(wg_id), v, mip, slice);
        }
    }
}

void spd_downsample_next_four(uint x, uint y, uvec2 wg_id, uint local_id, uint base_mip, uint mips, uint slice)
{
    if (mips <= base_mip) return;
    barrier();
    spd_downsample_mip_2(x, y, wg_id, local_id, base_mip, slice);

    if (mips <= base_mip + 1) return;
    barrier();
    spd_downsample_mip_3(x, y, wg_id, local_id, base_mip + 1, slice);

    if (mips <= base_mip + 2) return;
    barrier();
    spd_downsample_mip_4(x, y, wg_id, local_id, base_mip + 2, slice);

    if (mips <= base_mip + 3) return;
    barrier();
    spd_downsample_mip_5(wg_id, local_id, base_mip + 3, slice);
}

bool spd_exit_workgroup(uint num_wgs, uint local_id, uint slice)
{
    // spd_counter must be shared, not local
    if (local_id == 0)
        spd_counter = atomicAdd(pc.spd_counter_buffer.counter, 1);

    barrier();

    // only 1 wg to proceed
    return spd_counter != (num_wgs - 1);
}

void spd_reset_atomic_counter(uint slice)
{
    pc.spd_counter_buffer.counter = 0;
}

void spd_downsample_mips_6_7(uint x, uint y, uint mips, uint slice)
{
    ivec2 tex = ivec2(x * 4 + 0, y * 4 + 0);
    ivec2 pix = ivec2(x * 2 + 0, y * 2 + 0);
    float v0 = spd_reduce_coherent_load(tex, slice);
    spd_store(pix, v0, 6, slice);

    tex = ivec2(x * 4 + 2, y * 4 + 0);
    pix = ivec2(x * 2 + 1, y * 2 + 0);
    float v1 = spd_reduce_coherent_load(tex, slice);
    spd_store(pix, v1, 6, slice);

    tex = ivec2(x * 4 + 0, y * 4 + 2);
    pix = ivec2(x * 2 + 0, y * 2 + 1);
    float v2 = spd_reduce_coherent_load(tex, slice);
    spd_store(pix, v2, 6, slice);

    tex = ivec2(x * 4 + 2, y * 4 + 2);
    pix = ivec2(x * 2 + 1, y * 2 + 1);
    float v3 = spd_reduce_coherent_load(tex, slice);
    spd_store(pix, v3, 6, slice);

    if (mips <= 7) return;
    // no barrier needed, working on values only from the same thread

    float v = spd_reduce_4(v0, v1, v2, v3);
    spd_store(ivec2(x, y), v, 7, slice);
    spd_store_intermediate(x, y, v);
}

void spd_downsample(uvec2 wg_id, uint local_id, uint mips, uint num_wgs, uint slice)
{
    // map to 2d shared memory
    uvec2 sub_xy = ARmpRed8x8(local_id % 64);
    uint x = sub_xy.x + 8 * ((local_id >> 6) % 2);
    uint y = sub_xy.y + 8 * ((local_id >> 7));

    spd_downsample_mips_0_1(x, y, wg_id, local_id, mips, slice);

    spd_downsample_next_four(x, y, wg_id, local_id, 2, mips, slice);

    if (mips <= 6) return;

    if (spd_exit_workgroup(num_wgs, local_id, slice)) return;

    // only 1 wg from here on out

    if (local_id == 0)
        spd_reset_atomic_counter(slice);

    spd_downsample_mips_6_7(x, y, mips, slice);
    spd_downsample_next_four(x, y, uvec2(0, 0), local_id, 8, mips, slice);
}

void main()
{
    spd_downsample(
        gl_WorkGroupID.xy,
        gl_LocalInvocationIndex,
        pc.mips,
        pc.num_wgs,
        gl_WorkGroupID.z
    );
}
