#version 450

#extension GL_GOOGLE_include_directive : require

#include "bindings.glsl"
#include "buffer_references.glsl"
#include "sh.glsl"

layout (local_size_x = 32) in;

layout (push_constant) uniform constants
{
	SHBuffer sh_buffer;
	uint cubemap_id;
};

shared SH9 shared_r[gl_WorkGroupSize.x];
shared SH9 shared_g[gl_WorkGroupSize.x];
shared SH9 shared_b[gl_WorkGroupSize.x];

const int samples = 100;

void main()
{
	SH9 R = sh_zero();
	SH9 G = sh_zero();
	SH9 B = sh_zero();

	// TODO: use more workgroups
	for (float phi = gl_LocalInvocationIndex + 0.5; phi < samples; phi = phi + gl_WorkGroupSize.x)
	{
		for (float theta = 0.5; theta < samples; theta++) 
		{
			vec3 dir = uniform_sample_sphere(phi * (1.0 / samples), theta * (1.0 / samples));
			
			SH9 base = sh_basis(dir);
			
			vec3 color = texture(samplerCube(textures_cube[cubemap_id], samplers[CUBE_SAMPLER]), dir).xyz;
			
			R = sh_sum(R, sh_scale(base, color.r));
			G = sh_sum(G, sh_scale(base, color.g));
			B = sh_sum(B, sh_scale(base, color.b));
		}
	}
	
	shared_r[gl_LocalInvocationIndex] = R;
	shared_g[gl_LocalInvocationIndex] = G;
	shared_b[gl_LocalInvocationIndex] = B;
	
	// TODO: technically not required for single workgroup single warp - to modify if using more workgroups/warps
	//memoryBarrier();
	//barrier();
	
	if (gl_LocalInvocationIndex == 0)
	{
		R = shared_r[0];
		G = shared_g[0];
		B = shared_b[0];
		
		for (int i = 1; i < gl_WorkGroupSize.x; i++)
		{
			R = sh_sum(shared_r[i], R);
			G = sh_sum(shared_g[i], G);
			B = sh_sum(shared_b[i], B);
		}
		
		float factor = (4 * PI) / (samples * samples);
		R = sh_scale(R, factor);
		G = sh_scale(G, factor);
		B = sh_scale(B, factor);
		
		SH9 coefficients;
		coefficients.c[0] = 3.141593 * 0.282095; 
		coefficients.c[1] = 2.094395 * -0.488603;
		coefficients.c[2] = 2.094395 * 0.488603;
		coefficients.c[3] = 2.094395 * -0.488603;
		coefficients.c[4] = 0.785398 * 1.092548;
		coefficients.c[5] = 0.785398 * -1.092548;
		coefficients.c[6] = 0.785398 * 0.315392;
		coefficients.c[7] = 0.785398 * -1.092548;
		coefficients.c[8] = 0.785398 * 0.546274;
		
		R = sh_mul(R, coefficients);
		G = sh_mul(G, coefficients);
		B = sh_mul(B, coefficients);
		
		sh_buffer.r_coefficients = R;
		sh_buffer.g_coefficients = G;
		sh_buffer.b_coefficients = B;
	}
}