#version 450

#extension GL_GOOGLE_include_directive : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_buffer_reference : require

#include "mesh.glsl"

layout (local_size_x = 1) in;

layout(buffer_reference, std430) buffer DispatchBuffer
{
	uint workgroupX;
	uint workgroupY;
	uint workgroupZ;
};

layout( push_constant ) uniform constants
{
	DispatchBuffer dispatchBuffer;
} pc;

void main()
{
	pc.dispatchBuffer.workgroupY = 1;
	pc.dispatchBuffer.workgroupZ = 1;
}